default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
      upload_to_play_store(
        track: "internal",
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: false,
        skip_upload_apk: true,
        aab: "../build/app/outputs/bundle/release/app-release.aab")
  end

end
