name: publish

on:
  workflow_dispatch:
    inputs:
      track:
        required: true

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' 
          bundler-cache: true 
      
      - name: Install bundle
        run: |
           cd sampleapp/android
           bundle config path vendor/bundle
           bundle install --jobs 4 --retry 3
          
      - name: Configure Keystore
        run: |
           cd sampleapp/android
           echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
           base64 -d -i keystore.jks.b64 > $(`echo pwd`)/keystore.jks
           echo "storeFile=$(`echo pwd`)/keystore.jks" >> local.properties
           echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> local.properties
           echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> local.properties
           echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> local.properties
           cat local.properties
        env:
           ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
           KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
           KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
           KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: Create Google Play Config file
        run : |
          cd sampleapp/android
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}

      - name: Flutter build
        run: |
          cd sampleapp
          sudo apt update
          sudo apt install snapd
          sudo snap install flutter --classic    
          flutter --version
          flutter build appbundle -v

      - name: Distribute app to ${{ github.event.inputs.track }} track 🚀
        run: |
          cd sampleapp/android
          cat local.properties
          bundle exec fastlane ${{ github.event.inputs.track }}


